name: pull-request
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: '10.x'
      - run: npm install
      - name: Run ESLint
        uses: icrawl/action-eslint@v1