name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '10.x'
      - run: npm install
      - name: eslint
        uses: icrawl/action-eslint@v1
        #with:
        #  custom-glob: 'src/**/*.ts' # only if a different glob is needed, default: src